"""
app/api/routes/alerts.py
GET /alerts — returns all Action Agent alerts stored in PostgreSQL.
"""
from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models.alert import Alert
from app.db.session import get_db

router = APIRouter()


class AlertResponse(BaseModel):
    id:          str
    session_id:  Optional[str]
    document_id: Optional[str]
    alert_type:  str
    message:     str
    severity:    str
    context:     Optional[str]
    created_at:  str

    class Config:
        from_attributes = True


@router.get(
    "/",
    response_model=List[AlertResponse],
    summary="List all Action Agent alerts",
)
async def list_alerts(
    severity:   Optional[str] = Query(default=None, description="Filter by severity: low|medium|high|critical"),
    alert_type: Optional[str] = Query(default=None, description="Filter by type: anomaly|contradiction|missing_clause"),
    document_id:Optional[str] = Query(default=None, description="Filter by document ID"),
    limit:      int            = Query(default=50, ge=1, le=200),
    offset:     int            = Query(default=0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns all alerts generated by the Action Agent, newest first.
    Supports filtering by severity, type, and document_id.
    """
    stmt = select(Alert).order_by(Alert.created_at.desc()).limit(limit).offset(offset)

    if severity:
        stmt = stmt.where(Alert.severity == severity)
    if alert_type:
        stmt = stmt.where(Alert.alert_type == alert_type)
    if document_id:
        stmt = stmt.where(Alert.document_id.contains(document_id))

    result = await db.execute(stmt)
    alerts = result.scalars().all()

    return [
        AlertResponse(
            id          = str(a.id),
            session_id  = a.session_id,
            document_id = a.document_id,
            alert_type  = a.alert_type,
            message     = a.message,
            severity    = a.severity.value,
            context     = a.context,
            created_at  = a.created_at.isoformat(),
        )
        for a in alerts
    ]
